Repository openWB/core, pull requests merged in 2023-10, with the labels that each got.

#1149 Bugfix
  packages/helpermodules/subdata.py
  packages/modules/internal_chargepoint_handler/internal_chargepoint_handler.py
  packages/modules/vehicles/bmw/api.py
  packages/modules/vehicles/smarteq/api.py
Labels: bug

#1142 tronity: check fix for empty/none access_token
  packages/modules/vehicles/tronity/api.py
Labels: bug

#1163 fix loadmanagement for sub counter
  packages/control/algorithm/additional_current.py
  packages/control/algorithm/algorithm.py
  packages/control/algorithm/common.py
  packages/control/algorithm/common_test.py
  packages/control/algorithm/min_current.py
  packages/control/algorithm/no_current.py
  packages/control/algorithm/surplus_controlled.py
Labels: bug

#1139 don't change rfid tag after charge start
  packages/control/chargepoint/chargepoint.py
Labels: bug

#1157 fix duration values of "0:60"
  packages/helpermodules/data_migration/data_migration.py
  packages/helpermodules/timecheck.py
  packages/helpermodules/update_config.py
Labels: bug

#1160 fix for tickets with simulator chargepoints
  packages/helpermodules/parse_send_debug.py
Labels: bug

#1055 backup_clouds-NFS adapter
  packages/modules/backup_clouds/nfs/__init__.py
  packages/modules/backup_clouds/nfs/backup_cloud.py
  packages/modules/backup_clouds/nfs/config.py
Labels: enhancement

#1081 Onedrive_Backup
  .github/workflows/github-actions-python.yml
  packages/helpermodules/command.py
  packages/modules/backup_clouds/onedrive/__init__.py
  packages/modules/backup_clouds/onedrive/api.py
  packages/modules/backup_clouds/onedrive/backup_cloud.py
  packages/modules/backup_clouds/onedrive/config.py
  packages/modules/backup_clouds/onedrive/msdrive/constants.py
  packages/modules/backup_clouds/onedrive/msdrive/drive.py
  packages/modules/backup_clouds/onedrive/msdrive/exceptions.py
  packages/modules/backup_clouds/onedrive/msdrive/onedrive.py
  packages/modules/conftest.py
  requirements.txt
Labels: enhancement

#1093 move control parameter to Chargepoint class
  packages/control/algorithm/additional_current.py
  packages/control/algorithm/additional_current_test.py
  packages/control/algorithm/algorithm.py
  packages/control/algorithm/common.py
  packages/control/algorithm/common_test.py
  packages/control/algorithm/filter_chargepoints.py
  packages/control/algorithm/filter_chargepoints_test.py
  packages/control/algorithm/integration_test/conftest.py
  packages/control/algorithm/integration_test/instant_charging_test.py
  packages/control/algorithm/integration_test/pv_charging_test.py
  packages/control/algorithm/surplus_controlled.py
  packages/control/algorithm/surplus_controlled_test.py
  packages/control/auto_phase_switch_test.py
  packages/control/chargelog.py
  packages/control/chargepoint/chargepoint.py
  packages/control/chargepoint/chargepoint_all.py
  packages/control/chargepoint/chargepoint_test.py
  packages/control/chargepoint/control_parameter.py
  packages/control/chargepoint/get_phases_test.py
  packages/control/counter.py
  packages/control/counter_test.py
  packages/control/ev.py
  packages/control/phase_switch.py
  packages/control/process.py
  packages/helpermodules/changed_values_handler.py
  packages/helpermodules/parse_send_debug.py
  packages/helpermodules/setdata.py
  packages/helpermodules/subdata.py
  packages/helpermodules/update_config.py
Labels: enhancement

#1121 Phasenumschaltung unter Beachtung der Schieflast
  packages/control/algorithm/additional_current.py
  packages/control/algorithm/algorithm.py
  packages/control/algorithm/integration_test/instant_charging_test.py
  packages/control/algorithm/min_current.py
  packages/control/algorithm/surplus_controlled.py
  packages/control/auto_phase_switch_test.py
  packages/control/chargepoint/chargepoint.py
  packages/control/chargepoint/control_parameter.py
  packages/control/ev.py
  packages/control/limiting_value.py
  packages/control/loadmanagement.py
  packages/helpermodules/setdata.py
Labels: enhancement

#1144 dynamic device selection
  packages/main.py
  packages/modules/internal_chargepoint_handler/rfid.py
Labels: enhancement

#1176 fix internal chargepoint handler
  packages/helpermodules/subdata.py
Labels: bug

#1088 Backup smb
  packages/modules/backup_clouds/samba/backup_cloud.py
  packages/modules/backup_clouds/samba/config.py
  packages/modules/conftest.py
  requirements.txt
Labels: enhancement

#1181 fix internal chargepoint
  packages/modules/internal_chargepoint_handler/internal_chargepoint_handler.py
  packages/modules/internal_chargepoint_handler/update_values_test.py
Labels: bug

#1182 bugfixes
  packages/control/chargepoint/chargepoint.py
  packages/control/ev.py
  packages/helpermodules/constants.py
  packages/helpermodules/data_migration/data_migration.py
  packages/helpermodules/subdata.py
  packages/helpermodules/timecheck.py
  packages/helpermodules/update_config.py
  packages/modules/common/component_state.py
  packages/modules/common/fault_state.py
  packages/modules/internal_chargepoint_handler/internal_chargepoint_handler_config.py
  packages/modules/update_soc.py
Labels: bug

#1193 fix soc subscription
  packages/helpermodules/subdata.py
Labels: bug

#1175 Backup
  runs/backup.sh
  runs/prepare_restore.sh
  runs/restore.sh
Labels: enhancement

#1197 fix switch off pv charging
  packages/control/algorithm/min_current.py
Labels: bug

#1199 fix unused evse current
  packages/control/algorithm/surplus_controlled.py
  packages/control/algorithm/surplus_controlled_test.py
Labels: bug

#1195 move efficiency to ev template
  packages/control/ev.py
  packages/helpermodules/update_config.py
  packages/modules/common/abstract_vehicle.py
  packages/modules/common/configurable_vehicle.py
  packages/modules/update_soc.py
Labels: enhancement

#1220 Bugfix
  packages/control/chargepoint/chargepoint.py
  packages/helpermodules/data_migration/data_migration.py
  packages/helpermodules/timecheck.py
  packages/helpermodules/timecheck_test.py
  packages/helpermodules/update_config.py
Labels: bug

#1214 kostal_pico_old configuration url
  packages/helpermodules/update_config.py
  packages/modules/devices/kostal_piko_old/config.py
  packages/modules/devices/kostal_piko_old/device.py
Labels: bug, ui

#1218 rct sends data even if it is in fault state
  packages/control/bat_all.py
  packages/helpermodules/changed_values_handler.py
  packages/helpermodules/setdata.py
  packages/helpermodules/update_config.py
  packages/main.py
  packages/modules/devices/rct/bat.py
  packages/modules/devices/rct/counter.py
Labels: bug

#1209 improve huawei request
  packages/modules/devices/huawei/bat.py
  packages/modules/devices/huawei/counter.py
  packages/modules/devices/huawei/device.py
  packages/modules/devices/huawei/inverter.py
Labels: bug

#1190 improve error handling datastore upgrade
  packages/helpermodules/update_config.py
Labels: bug
