Repository openWB/core, pull requests merged in 2023-08, with the labels that each got.

#1061 fix amount limit
  packages/control/chargepoint/chargepoint.py
  packages/control/ev.py
  packages/helpermodules/setdata.py
  packages/helpermodules/update_config.py
Labels: bug

#1049 pv Leistung und Chargestatus für Openwb 2.0
  packages/smarthome/smarthome.py
Labels: bug

#1051 Repair hierarchy
  packages/control/counter_all.py
  packages/control/hierarchy_test.py
  packages/main.py
  packages/modules/common/component_type.py
Labels: bug

#1029 Soc Kia
  packages/modules/vehicles/kia/__init__.py
  packages/modules/vehicles/kia/api.py
  packages/modules/vehicles/kia/config.py
  packages/modules/vehicles/kia/soc.py
Labels: enhancement

#968 Onedrive_Backup
  .github/workflows/github-actions-python.yml
  packages/helpermodules/command.py
  packages/modules/backup_clouds/onedrive/__init__.py
  packages/modules/backup_clouds/onedrive/api.py
  packages/modules/backup_clouds/onedrive/backup_cloud.py
  packages/modules/backup_clouds/onedrive/config.py
  packages/modules/backup_clouds/onedrive/msdrive/constants.py
  packages/modules/backup_clouds/onedrive/msdrive/drive.py
  packages/modules/backup_clouds/onedrive/msdrive/exceptions.py
  packages/modules/backup_clouds/onedrive/msdrive/onedrive.py
  requirements.txt
Labels: enhancement

#1044 add solarmax bat
  packages/helpermodules/update_config.py
  packages/modules/devices/solarmax/bat.py
  packages/modules/devices/solarmax/config.py
  packages/modules/devices/solarmax/device.py
  packages/modules/devices/solarmax/inverter.py
Labels: enhancement

#1059 phase powers and currents added
  packages/modules/devices/json/config.py
  packages/modules/devices/json/counter.py
  packages/modules/devices/json/device.py
  packages/modules/devices/json/device_test.py
Labels: enhancement

#1085 Bugfix
  data/config/boot_config.txt
  packages/helpermodules/messaging.py
  packages/helpermodules/update_config.py
  runs/atreboot.sh
Labels: bug

#1112 Changes snaptec repo
  packages/modules/devices/batterx/batterx_test.py
  packages/modules/devices/batterx/device.py
Labels: bug

#1111 setdata powers and frequency
  packages/helpermodules/setdata.py
Labels: bug

#1113 default value datastore version
  packages/helpermodules/update_config.py
Labels: enhancement

#1117 Feature home consumption in log data
  packages/control/bat_all.py
  packages/control/counter_all.py
  packages/control/counter_home_consumption_test.py
  packages/control/pv_all.py
  packages/helpermodules/measurement_logging/conftest.py
  packages/helpermodules/measurement_logging/process_log.py
  packages/helpermodules/measurement_logging/update_daily_yields.py
  packages/helpermodules/measurement_logging/write_log.py
  packages/helpermodules/setdata.py
  packages/helpermodules/subdata.py
  packages/helpermodules/update_config.py
Labels: enhancement, ui

#1094 Feature timeout soc
  packages/main.py
  packages/modules/update_soc.py
Labels: bug

#1120 fix control range
  packages/control/auto_phase_switch_test.py
  packages/control/counter.py
  packages/control/ev.py
Labels: bug
