Repository openWB/core, pull requests merged in 2023-12, with the labels that each got.

#1229 fix validate hierarchy if evu counter is missing
  packages/control/counter_all.py
Labels: bug

#1226 add power_source to graph data
  packages/helpermodules/measurement_logging/process_log.py
  packages/helpermodules/measurement_logging/process_log_test.py
Labels: enhancement

#1288 Fix surplus controlled
  packages/control/algorithm/integration_test/pv_charging_test.py
  packages/control/bat_all.py
  packages/control/bat_all_test.py
  packages/control/counter.py
  packages/control/counter_test.py
  packages/helpermodules/setdata.py
Labels: bug

#1227 Failed phase switches
  packages/control/chargepoint/chargepoint.py
  packages/control/chargepoint/control_parameter.py
  packages/control/general.py
  packages/helpermodules/setdata.py
  packages/helpermodules/update_config.py
Labels: enhancement

#1315 fix fault state handling
  packages/modules/chargepoints/smartwb/chargepoint_module.py
  packages/modules/devices/lg/bat.py
  packages/modules/devices/rct/bat.py
  packages/modules/devices/rct/counter.py
  packages/modules/internal_chargepoint_handler/internal_chargepoint_handler.py
Labels: bug

#1316 fix logging evse version
  packages/modules/common/evse.py
  packages/modules/internal_chargepoint_handler/chargepoint_module.py
Labels: bug

#1318 fix missing timecheck function
  packages/helpermodules/timecheck.py
Labels: bug

#1311 remove outdated rollup plugin
  packages/modules/display_themes/cards/source/package-lock.json
  packages/modules/display_themes/cards/source/package.json
  packages/modules/display_themes/cards/source/vite.config.js
Labels: dependencies

#1307 catch exception in component_state.py
  packages/modules/common/component_state.py
Labels: bug
