Repository openWB/core, pull requests merged in 2023-11, with the labels that each got.

#1232 fix bat all values
  packages/control/bat_all.py
  packages/helpermodules/measurement_logging/update_daily_yields.py
  packages/helpermodules/measurement_logging/update_daily_yields_test.py
  packages/helpermodules/update_config.py
  packages/main.py
Labels: bug

#1233 fix late bat values
  packages/main.py
  packages/modules/loadvars.py
  packages/modules/update_soc.py
  packages/modules/utils.py
Labels: bug

#1239 fix smartfox
  packages/modules/devices/smartfox/device.py
Labels: bug

#1187 Update samba Modul
  docs/Cloud-Sicherung.md
  docs/Samba als Sicherung einrichten.md
  docs/Samba.png
  docs/_Sidebar.md
  packages/modules/backup_clouds/samba/backup_cloud.py
  packages/modules/backup_clouds/samba/config.py
Labels: bug, ui

#1238 Modbus-API: send "None" if no tag is scanned
  packages/helpermodules/modbusserver.py
  packages/modbus_control_tester.py
Labels: bug

#1245 Theme selection
  packages/helpermodules/update_config.py
  packages/modules/configuration.py
  packages/modules/display_themes/cards/config.py
  packages/modules/web_themes/standard_legacy/config.py
Labels: enhancement

#1251 Fix SoC openWB pro
  packages/conftest.py
  packages/helpermodules/subdata.py
  packages/helpermodules/timecheck.py
  packages/helpermodules/update_config.py
  packages/modules/common/abstract_vehicle.py
  packages/modules/common/configurable_vehicle.py
  packages/modules/common/configurable_vehicle_test.py
  packages/modules/update_soc.py
Labels: bug

#1254 fix hardware check
  packages/modules/internal_chargepoint_handler/clients.py
Labels: bug

#1260 hotfix for one and two phase openWB
  packages/modules/internal_chargepoint_handler/clients.py
  packages/modules/internal_chargepoint_handler/clients_test.py
Labels: bug

#1265 Fix MQTT SoC
  packages/modules/common/configurable_vehicle.py
  runs/send_debug.sh
Labels: bug

#1268 fix soc source
  packages/modules/common/configurable_vehicle.py
  packages/modules/common/configurable_vehicle_test.py
Labels: bug

#1278 fix phases scheduled charging
  packages/control/ev.py
  packages/control/ev_charge_template_test.py
Labels: bug

#1280 fix soc set to 0
  packages/modules/common/configurable_vehicle.py
Labels: bug

#1283 fix manual soc
  packages/modules/common/configurable_vehicle.py
Labels: bug
