Repository openWB/core, pull requests merged in 2024-01, with the labels that each got.

#1324 Fix control range
  packages/control/algorithm/integration_test/pv_charging_test.py
  packages/control/counter.py
  packages/control/counter_test.py
Labels: bug

#1353 fix voltego
  packages/modules/electricity_tariffs/voltego/tariff.py
Labels: bug

#1355 fix calculated soc
  packages/modules/update_soc.py
  packages/modules/update_soc_test.py
Labels: bug

#1359 Persistent Logging for data migration
  packages/helpermodules/data_migration/data_migration.py
  packages/helpermodules/logger.py
Labels: enhancement, ui

#1361 fix charge cost
  packages/control/chargelog/chargelog.py
  packages/control/chargelog/chargelog_test.py
  packages/helpermodules/measurement_logging/process_log.py
  packages/helpermodules/measurement_logging/write_log.py
  packages/main.py
Labels: bug

#1363 fix daily log date
  packages/helpermodules/update_config.py
Labels: bug

#1370 small fixes
  packages/modules/devices/fronius/config.py
  packages/modules/devices/fronius/counter_sm.py
  packages/modules/web_themes/standard_legacy/web/index.html
Labels: bug

#1372 fix sequence of scheduled tasks for charge cost calculation
  packages/main.py
Labels: bug

#1329 RSE via IO-Lan or GPIO
  packages/control/chargepoint/chargepoint.py
  packages/control/general.py
  packages/control/prepare.py
  packages/helpermodules/data_migration/data_migration.py
  packages/helpermodules/hardware_configuration.py
  packages/helpermodules/setdata.py
  packages/helpermodules/subdata.py
  packages/helpermodules/update_config.py
  packages/modules/common/component_state.py
  packages/modules/common/component_type.py
  packages/modules/common/configurable_ripple_control_receiver.py
  packages/modules/common/fault_state.py
  packages/modules/common/modbus.py
  packages/modules/common/store/__init__.py
  packages/modules/common/store/_ripple_control_receiver.py
  packages/modules/configuration.py
  packages/modules/loadvars.py
  packages/modules/ripple_control_receiver.py
  packages/modules/ripple_control_receivers/gpio/__init__.py
  packages/modules/ripple_control_receivers/gpio/config.py
  packages/modules/ripple_control_receivers/gpio/ripple_control_receiver.py
  packages/modules/ripple_control_receivers/io_lan_hf/__init__.py
  packages/modules/ripple_control_receivers/io_lan_hf/config.py
  packages/modules/ripple_control_receivers/io_lan_hf/ripple_control_receiver.py
Labels: enhancement

#1377 fix phases for cps without phase switch
  packages/control/chargepoint/chargepoint.py
  packages/control/chargepoint/get_phases_test.py
Labels: bug

#1369 fix totals percentage for diagram sum
  packages/helpermodules/measurement_logging/process_log.py
Labels: bug

#1388 fix pub fault_str/state to parent
  packages/modules/common/fault_state.py
Labels: bug

#1389 fix fault state handling for no duos
  packages/modules/internal_chargepoint_handler/internal_chargepoint_handler.py
Labels: bug

#1390 time charging, autolock: fix end of month
  packages/helpermodules/timecheck.py
Labels: bug

#1385 fix no module selected for rse and electronic tariff
  packages/helpermodules/subdata.py
Labels: bug
