Repository openWB/core, pull requests merged in 2024-07, with the labels that each got.

#1733 Colors theme: Fix and update
  packages/modules/web_themes/colors/source/src/assets/js/themeConfig.ts
  packages/modules/web_themes/colors/source/src/assets/js/types.ts
  packages/modules/web_themes/colors/source/src/components/buttonBar/BBSelect.vue
  packages/modules/web_themes/colors/source/src/components/chargePointList/cpConfig/CPChargeConfig.vue
  packages/modules/web_themes/colors/source/src/components/chargePointList/cpConfig/CPConfigPv.vue
  packages/modules/web_themes/colors/source/src/components/powerGraph/PGSourceGraph.vue
  packages/modules/web_themes/colors/web/assets/index-C5LmjOEn.css
  packages/modules/web_themes/colors/web/assets/index-DNPzLOl7.js
  packages/modules/web_themes/colors/web/assets/index-I7LQK7it.js
  packages/modules/web_themes/colors/web/index.html
Labels: bug, enhancement

#1693 Colors Display theme: added functions, code cleanup
  packages/modules/display_themes/colors/config.py
  packages/modules/display_themes/colors/source/package.json
  packages/modules/display_themes/colors/source/src/assets/js/model.ts
  packages/modules/display_themes/colors/source/src/assets/js/mqttClient.ts
  packages/modules/display_themes/colors/source/src/assets/js/processMessages.ts
  packages/modules/display_themes/colors/source/src/assets/js/themeConfig.ts
  packages/modules/display_themes/colors/source/src/assets/js/types.ts
  packages/modules/display_themes/colors/source/src/components/HelloWorld.vue
  packages/modules/display_themes/colors/source/src/components/TheWelcome.vue
  packages/modules/display_themes/colors/source/src/components/WelcomeItem.vue
  packages/modules/display_themes/colors/source/src/components/chargePointList/CPChargePoint.vue
  packages/modules/display_themes/colors/source/src/components/powerGraph/processLiveGraphData.ts
  packages/modules/display_themes/colors/source/src/components/shared/DisplayButton.vue
  packages/modules/display_themes/colors/source/src/components/shared/ModalComponent.vue
  packages/modules/display_themes/colors/source/src/components/shared/NumberPad.vue
  packages/modules/display_themes/colors/source/src/components/shared/PadButton.vue
  packages/modules/display_themes/colors/source/src/components/statusPage/StatusPage.vue
  packages/modules/display_themes/colors/source/src/main.ts
  packages/modules/display_themes/colors/source/src/router/index.ts
  packages/modules/display_themes/colors/source/src/views/DisplayTheme.vue
  packages/modules/display_themes/colors/source/src/views/NavigationBar.vue
  packages/modules/display_themes/colors/web/assets/index-Bx6sNqKP.css
  packages/modules/display_themes/colors/web/assets/index-CA9GRpRt.js
  packages/modules/display_themes/colors/web/assets/index-CSvZCM9T.js
  packages/modules/display_themes/colors/web/assets/vendor-B-lkTxtL.js
  packages/modules/display_themes/colors/web/assets/vendor-U1h4_w4Q.js
  packages/modules/display_themes/colors/web/index.html
Labels: enhancement, dependencies

#1748 minor fixes
  packages/modules/backup_clouds/samba/config.py
Labels: bug

#1770 Feature secondary display
  packages/helpermodules/command.py
  packages/modules/display_themes/cards/source/package-lock.json
  packages/modules/display_themes/cards/source/src/App.vue
  packages/modules/display_themes/cards/source/src/components/NumberPad.vue
  packages/modules/display_themes/cards/source/src/components/Status/RebootButton.vue
  packages/modules/display_themes/cards/source/src/components/Status/ShutdownButton.vue
  packages/modules/display_themes/cards/source/src/stores/mqtt.js
  packages/modules/display_themes/cards/source/src/views/ChargePointsView.vue
  web/display/index.html
  web/display/processAllMqttMsg.js
  web/display/setupMqttServices.js
  web/display/style.css
Labels: bug
