Repository openWB/core, pull requests merged in 2024-03, with the labels that each got.

#1453 fix peaks caused by inverter sending 0
  packages/control/chargelog/chargelog.py
  packages/helpermodules/measurement_logging/process_log.py
  packages/helpermodules/measurement_logging/write_log.py
  packages/helpermodules/measurement_logging/write_log_test.py
Labels: bug

#1455 bugfix
  packages/helpermodules/graph.py
  runs/update_available_versions.sh
Labels: bug

#1461 fixes: standard theme
  packages/modules/web_themes/standard_legacy/web/index.html
  packages/modules/web_themes/standard_legacy/web/livechart.js
  packages/modules/web_themes/standard_legacy/web/processAllMqttMsg.js
Labels: bug

#1464 fix simcount in case of error, fix zero values if there is no previous value
  packages/helpermodules/measurement_logging/write_log.py
  packages/helpermodules/measurement_logging/write_log_test.py
  packages/modules/common/simcount/_simcount.py
Labels: bug

#1466 fix ev chart labels
  packages/modules/web_themes/standard_legacy/web/index.html
  packages/modules/web_themes/standard_legacy/web/livechart.js
  packages/modules/web_themes/standard_legacy/web/processAllMqttMsg.js
Labels: bug

#1467 fix mpm3pm power factors
  packages/modules/common/mpm3pm.py
Labels: bug

#1471 fix log names
  packages/helpermodules/measurement_logging/process_log.py
  packages/helpermodules/measurement_logging/write_log.py
  packages/helpermodules/update_config.py
  packages/helpermodules/utils/topic_parser.py
Labels: bug

#1477 Fixes Standard Theme
  packages/modules/web_themes/standard_legacy/web/helperFunctions.js
  packages/modules/web_themes/standard_legacy/web/index.html
  packages/modules/web_themes/standard_legacy/web/processAllMqttMsg.js
Labels: bug

#1487 Release hotfix
  .gitignore
  packages/helpermodules/measurement_logging/write_log.py
Labels: bug

#1443 scheduled charging: remaining time less than duration
  packages/control/ev.py
  packages/control/ev_charge_template_test.py
Labels: bug

#1472 fix reserved power for phase switch
  packages/control/algorithm/integration_test/pv_charging_test.py
  packages/control/ev.py
Labels: bug

#1498 fix modbus write
  packages/modules/common/modbus.py
Labels: bug

#1323 Feature secure broker
  data/config/apache/000-default.conf
  data/config/apache/apache-openwb-ssl.conf
  data/config/mosquitto/mosquitto.acl
  data/config/mosquitto/mosquitto.conf
  data/config/mosquitto/mosquitto_local.conf
  data/config/mosquitto/mosquitto_local_init
  data/config/mosquitto/openwb.conf
  data/config/mosquitto/openwb_local.conf
  data/config/openwb.conf
  openwb-install.sh
  packages/modules/web_themes/standard_legacy/web/index.html
  packages/modules/web_themes/standard_legacy/web/livechart.js
  packages/modules/web_themes/standard_legacy/web/processAllMqttMsg.js
  packages/modules/web_themes/standard_legacy/web/setupMqttServices.js
  runs/atreboot.sh
  runs/remoteSupport/remoteSupport.py
Labels: bug, enhancement

#1422 add Shelly Pro3EM as inverter to shelly module
  packages/modules/devices/shelly/inverter.py
Labels: enhancement, ui

#1500 dynamic sleep on mosquitto stop
  runs/atreboot.sh
Labels: bug

#1503 fix chargelog sum
  packages/control/chargelog/chargelog.py
Labels: bug
