Repository openWB/core, pull requests merged in 2024-11, with the labels that each got.

#1999 fix fronius component update
  packages/modules/devices/fronius/fronius/device.py
Labels: bug

#2002 Minor Bugfixes
  packages/control/chargelog/chargelog.py
  packages/modules/web_themes/standard_legacy/web/index.html
Labels: bug, ui

#2004 update cards display theme dependencies
  packages/modules/display_themes/cards/source/package-lock.json
  packages/modules/display_themes/cards/source/package.json
Labels: dependencies

#2032 Satellit: Fix telnet
  packages/modules/chargepoints/openwb_series2_satellit/chargepoint_module.py
Labels: bug
