Repository openWB/core, pull requests merged in 2024-04, with the labels that each got.

#1506 fix rundown power for hybrid systems
  packages/control/bat_all.py
  packages/control/bat_all_test.py
Labels: bug

#1507 fix range charged in chargelog
  packages/control/chargelog/chargelog.py
Labels: bug

#1486 MQTT-Topic "set/current" wird falsch mit "phases_to_use" beschrieben
  packages/modules/internal_chargepoint_handler/internal_chargepoint_handler.py
Labels: bug

#1383 Voltego: catch regenerated token
  packages/modules/electricity_tariffs/voltego/tariff.py
Labels: bug

#1511 Filter versions
  runs/update_available_versions.sh
Labels: enhancement, ui

#752 device_tasmota: new counter device
  packages/modules/common/tasmota.py
  packages/modules/devices/tasmota/__init__.py
  packages/modules/devices/tasmota/config.py
  packages/modules/devices/tasmota/counter.py
  packages/modules/devices/tasmota/device.py
Labels: enhancement

#1584 Fixes
  packages/helpermodules/update_config.py
  packages/modules/web_themes/standard_legacy/web/index.html
Labels: bug, enhancement

#1590 fix setdata message parsing
  packages/helpermodules/setdata.py
Labels: bug
