Repository openWB/core, pull requests merged in 2024-09, with the labels that each got.

#1789 Update requirements.txt for BMW (Bimmer)
  requirements.txt
Labels: help wanted

#1873 fix chargepoint state / pv switch off
  packages/control/phase_switch.py
  packages/modules/chargepoints/mqtt/chargepoint_module.py
Labels: bug

#1876 fix migration without bat values
  packages/helpermodules/data_migration/data_migration.py
Labels: bug

#1794 add possibility to invert external inverter power
  packages/helpermodules/update_config.py
  packages/modules/devices/solaredge/config.py
  packages/modules/devices/solaredge/external_inverter.py
Labels: enhancement, ui

#1830 Feature extended debug info
  data/config/mosquitto/openwb_local.conf
  packages/control/ev.py
  packages/helpermodules/hardware_configuration.py
  packages/helpermodules/modbusserver.py
  packages/helpermodules/setdata.py
  packages/helpermodules/update_config.py
  packages/modules/common/component_setup.py
Labels: enhancement, ui

#1877 SolarEdge: Use synergy units of the inverter to which the meters are connected
  packages/modules/devices/solaredge/device.py
Labels: bug

#1892 use ComponentSetup
  packages/modules/devices/mqtt/config.py
Labels: bug

#1859 consider bat regulate up == True in case of automatic phase switch 3p1p
  packages/control/bat_all.py
  packages/control/bat_all_test.py
  packages/control/chargepoint/chargepoint.py
  packages/control/counter.py
Labels: bug

#1897 fix missed vendor information
  packages/modules/devices/sigenergy/sigenergy/config.py
  packages/modules/devices/solis/solis/config.py
Labels: bug

#1906 updated gui samples
  docs/samples/samples_gui/backup_cloud.vue
  docs/samples/samples_gui/bat.vue
  docs/samples/samples_gui/counter.vue
  docs/samples/samples_gui/device.vue
  docs/samples/samples_gui/inverter.vue
  docs/samples/samples_gui/vehicle.vue
Labels: documentation
