Repository openWB/core, pull requests merged in 2024-02, with the labels that each got.

#1397 fems: support multiple and single segment regex rqeuests
  packages/modules/devices/fems/bat.py
  packages/modules/devices/fems/counter.py
  packages/modules/devices/fems/device.py
  packages/modules/devices/fems/inverter.py
  packages/modules/devices/fems/version.py
Labels: bug

#1401 Duo+RFID: fix matching if other cp is plugged
  packages/control/chargepoint/chargepoint_test.py
  packages/control/chargepoint/rfd_test.py
  packages/control/chargepoint/rfid.py
Labels: bug

#1403 RCT: 0.5s sleep between server connections
  packages/modules/devices/rct/device.py
Labels: bug

#1408 fix analyzing percentages
  packages/helpermodules/measurement_logging/process_log.py
  packages/modules/web_themes/standard_legacy/web/index.html
Labels: bug

#1412 Bugfix
  packages/control/ev.py
  packages/helpermodules/changed_values_handler.py
  packages/helpermodules/data_migration/data_migration.py
  packages/main.py
Labels: bug

#1416 Use shorter name pattern for monthly_log data migration
  packages/helpermodules/data_migration/data_migration.py
Labels: bug

#1415 Fix missing house consumption log entries after data migration
  packages/helpermodules/measurement_logging/process_log.py
Labels: bug

#1417 Bugfix
  packages/helpermodules/measurement_logging/process_log.py
  packages/modules/common/utils/component_parser.py
Labels: bug

#1420 B23 meter: fix data types and adding powers per phase
  packages/modules/common/b23.py
Labels: bug

#1418 refactoring: reduce code duplication
  packages/helpermodules/measurement_logging/process_log.py
Labels: enhancement

#1426 fix ev status message
  packages/control/ev.py
Labels: bug

#1432 Fix b23
  packages/modules/common/b23.py
  packages/modules/common/component_state.py
Labels: bug

#1395 Wiki: Tags nur im Fahrzeug eintragen, Hybrid-Wechselrichter
  docs/Hybrid System aus Wechselrichter und Speicher.md
  docs/Ladung nur nach Freischaltung.md
Labels: ui

#1437 Virtual Counter: fix calculation for hybrid hierarchy
  packages/conftest.py
  packages/control/bat.py
  packages/control/conftest.py
  packages/control/counter_all.py
  packages/control/counter_home_consumption_test.py
  packages/control/hierarchy_test.py
  packages/modules/common/store/_counter.py
  packages/modules/devices/virtual/counter_test.py
Labels: bug

#1442 fix parse debug data for intermediate meter
  packages/helpermodules/parse_send_debug.py
Labels: bug

#1445 reset chargepoint values to default, keep meter values of cp, pv all and bat all
  packages/control/bat_all.py
  packages/control/pv_all.py
  packages/helpermodules/setdata.py
  packages/modules/internal_chargepoint_handler/chargepoint_module.py
Labels: bug
