Repository openWB/core, pull requests merged in 2024-10, with the labels that each got.

#1888 Feature cards display
  packages/modules/display_themes/cards/source/package-lock.json
  packages/modules/display_themes/cards/source/package.json
  packages/modules/display_themes/cards/source/src/App.vue
  packages/modules/display_themes/cards/source/src/components/DateTime.vue
  packages/modules/display_themes/cards/source/src/components/LockNavItem.vue
  packages/modules/display_themes/cards/source/src/components/TouchBlocker.vue
Labels: enhancement, dependencies

#1896 fix hardware configuration file
  data/config/configuration.json
  packages/helpermodules/hardware_configuration.py
  packages/helpermodules/update_config.py
Labels: bug

#1911 fix parsing local charge point id
  packages/modules/display_themes/cards/source/src/App.vue
Labels: bug

#1854 handle offline boot
  runs/atreboot.sh
  runs/setup_network.sh
Labels: enhancement

#1890 implement local display detection on rpi
  packages/helpermodules/update_config.py
  runs/atreboot.sh
  runs/update_local_display.sh
Labels: enhancement

#1913 update npm packages for colors display
  packages/modules/display_themes/colors/source/package-lock.json
  packages/modules/display_themes/colors/source/package.json
Labels: dependencies

#1941 fix typo
  packages/control/bat.py
  packages/control/bat_all.py
  packages/control/bat_all_test.py
  packages/control/process.py
  packages/helpermodules/setdata.py
  packages/helpermodules/update_config.py
Labels: ui

#1949 fix error timer chargepoints
  packages/helpermodules/utils/error_counter.py
  packages/modules/chargepoints/openwb_pro/chargepoint_module_test.py
Labels: bug

#1950 fix surplus charging for pv charging - submode instant charging
  packages/control/algorithm/surplus_controlled.py
Labels: bug

#1952 fix 3p1p mit Minimalem Dauerstrom
  packages/control/ev.py
Labels: bug

#1977 fix deviating evse current only if chargepoint is in charging state
  packages/control/algorithm/surplus_controlled.py
Labels: bug
