Repository openWB/core, pull requests merged in 2025-01, with the labels that each got.

#2109 remove spaces
  runs/install_packages.sh
Labels: bug

#2110 Colors theme (web): Fixes and version upgrades
  packages/modules/web_themes/colors/source/.eslintrc
  packages/modules/web_themes/colors/source/eslint.config.js
  packages/modules/web_themes/colors/source/package.json
  packages/modules/web_themes/colors/source/src/assets/js/processMessages.ts
  packages/modules/web_themes/colors/source/src/assets/js/themeConfig.ts
  packages/modules/web_themes/colors/source/src/components/batteryList/processMessages.ts
  packages/modules/web_themes/colors/source/src/components/chargePointList/processMessages.ts
  packages/modules/web_themes/colors/source/src/components/energyMeter2/EnergyLabel.vue
  packages/modules/web_themes/colors/source/src/components/powerGraph/PgSoc.vue
  packages/modules/web_themes/colors/source/src/components/powerMeter/PowerMeter.vue
  packages/modules/web_themes/colors/source/src/components/priceChart/GlobalPriceChart.vue
  packages/modules/web_themes/colors/source/src/components/priceChart/PriceChart.vue
  packages/modules/web_themes/colors/source/src/components/shared/DateInput.vue
  packages/modules/web_themes/colors/source/src/components/shared/RangeInput.vue
  packages/modules/web_themes/colors/source/src/components/smartHome/processMessages.ts
  packages/modules/web_themes/colors/source/src/views/ThemeSettings.vue
  packages/modules/web_themes/colors/web/assets/index-BPb-wTT5.css
  packages/modules/web_themes/colors/web/assets/index-Bpw8XWwo.js
  packages/modules/web_themes/colors/web/assets/index-SkrqAaaZ.js
  packages/modules/web_themes/colors/web/assets/vendor-BMda9Kth.js
  packages/modules/web_themes/colors/web/assets/vendor-CyQtMzsz.js
  packages/modules/web_themes/colors/web/index.html
Labels: bug, enhancement, dependencies

#2129 fix deye devicetype
  packages/modules/devices/deye/deye/bat.py
  packages/modules/devices/deye/deye/counter.py
  packages/modules/devices/deye/deye/device.py
  packages/modules/devices/deye/deye/inverter.py
Labels: bug

#2138 fix empty files in yearly download
  web/settings/downloadChargeLog.php
Labels: bug

#2139 switch from ping to curl for inet check
  runs/setup_network.sh
Labels: enhancement

#2140 fix solaredge: don't remove component from hierarchy
  packages/modules/devices/solaredge/solaredge/device.py
Labels: bug

#2155 fix phase switch
  packages/control/chargepoint/chargepoint.py
Labels: bug

#2159 reload display after 2 days
  web/display/index.html
Labels: bug

#2162 updated dependencies
  packages/modules/display_themes/cards/source/package-lock.json
Labels: dependencies

#2161 Colors theme display: Fixes, Reload/Shutdown-Buttons
  packages/modules/display_themes/colors/source/package-lock.json
  packages/modules/display_themes/colors/source/package.json
  packages/modules/display_themes/colors/source/src/App.vue
  packages/modules/display_themes/colors/source/src/assets/js/model.ts
  packages/modules/display_themes/colors/source/src/assets/js/processMessages.ts
  packages/modules/display_themes/colors/source/src/assets/js/sendMessages.ts
  packages/modules/display_themes/colors/source/src/assets/js/themeConfig.ts
  packages/modules/display_themes/colors/source/src/components/chargePointList/CPVehicle.vue
  packages/modules/display_themes/colors/source/src/components/energyMeter/EnergyMeter.vue
  packages/modules/display_themes/colors/source/src/components/powerGraph/model.ts
  packages/modules/display_themes/colors/source/src/components/powerMeter/PMUsageArc.vue
  packages/modules/display_themes/colors/source/src/components/shared/WBWidget.vue
  packages/modules/display_themes/colors/source/src/components/smartHome/model.ts
  packages/modules/display_themes/colors/source/src/components/smartHome/processMessages.ts
  packages/modules/display_themes/colors/source/src/views/DisplayTheme.vue
  packages/modules/display_themes/colors/source/src/views/NavigationBar.vue
  packages/modules/display_themes/colors/source/src/views/StatusPage.vue
Labels: bug, enhancement

#2174 Colors theme fixes
  packages/modules/web_themes/colors/source/package.json
  packages/modules/web_themes/colors/source/src/components/powerGraph/PgSoc.vue
  packages/modules/web_themes/colors/source/src/components/powerGraph/PgSourceGraph.vue
  packages/modules/web_themes/colors/source/src/components/powerGraph/PgUsageGraph.vue
  packages/modules/web_themes/colors/source/src/components/powerGraph/PgXAxis.vue
  packages/modules/web_themes/colors/source/src/components/powerGraph/PowerGraph.vue
  packages/modules/web_themes/colors/source/src/components/powerMeter/PowerMeter.vue
  packages/modules/web_themes/colors/source/src/views/ColorsTheme.vue
  packages/modules/web_themes/colors/web/assets/index-BM5jgL8d.css
  packages/modules/web_themes/colors/web/assets/index-Bpw8XWwo.js
  packages/modules/web_themes/colors/web/assets/index-CIr-OUyK.js
  packages/modules/web_themes/colors/web/assets/vendor-CmSLe-Fc.js
  packages/modules/web_themes/colors/web/assets/vendor-CyQtMzsz.js
  packages/modules/web_themes/colors/web/index.html
Labels: bug
