Repository openWB/core, pull requests merged in 2025-04, with the labels that each got.

#2272 [FIX] OCPP should use UTC instead of local time
  packages/control/ocpp.py
Labels: bug

#2299 check power limit controlable
  docs/Neues Modul programmieren.md
  docs/samples/sample_modbus/bat.py
  docs/samples/sample_request_by_component/bat.py
  docs/samples/sample_request_by_device/bat.py
  packages/control/bat_all.py
  packages/modules/common/abstract_device.py
  packages/modules/devices/generic/mqtt/bat.py
  packages/modules/devices/generic/mqtt/config.py
Labels: enhancement, ui

#2308 updated dependencies
  packages/modules/display_themes/cards/source/package-lock.json
  packages/modules/display_themes/cards/source/package.json
Labels: dependencies

#2282 Wiki for SoC Modules bmwbc, ovms, vwid: various improvements, additions
  docs/SoC-BMW-19-settings-1.PNG
  docs/SoC-BMW-19-settings-2.PNG
  docs/SoC-BMW-19-settings-3.PNG
  docs/SoC-BMW-19-settings-4.PNG
  docs/SoC-BMW-20-settings-1.PNG
  docs/SoC-BMW-20-settings-2.PNG
  docs/SoC-BMW-20-settings-3.PNG
  docs/SoC-BMW-Mini.md
  docs/SoC-OVMS-19-settings-1.PNG
  docs/SoC-OVMS-19-settings-2.PNG
  docs/SoC-OVMS.md
  docs/SoC-VWId-19-settings-1.PNG
  docs/SoC-VWId-19-settings-2.PNG
  docs/SoC-VWId-20-settings-1.PNG
  docs/SoC-VWId-20-settings-2.PNG
  docs/SoC-VWId.md
Labels: documentation

#2287 Force SoC-Update after chargestop
  packages/control/chargepoint/chargepoint.py
  packages/control/chargepoint/chargepoint_data.py
  packages/helpermodules/setdata.py
  packages/helpermodules/update_config.py
Labels: enhancement

#2271 disable warning
  packages/modules/common/req.py
Labels: enhancement

#2092 sonnenbatterie power control
  packages/modules/devices/sonnen/sonnenbatterie/bat.py
  packages/modules/devices/sonnen/sonnenbatterie/config.py
  packages/modules/devices/sonnen/sonnenbatterie/counter.py
  packages/modules/devices/sonnen/sonnenbatterie/counter_consumption.py
  packages/modules/devices/sonnen/sonnenbatterie/device.py
  packages/modules/devices/sonnen/sonnenbatterie/inverter.py
Labels: enhancement, ui

#2313 Feature official modules
  packages/helpermodules/update_config.py
  packages/modules/backup_clouds/nextcloud/config.py
  packages/modules/backup_clouds/nfs/config.py
  packages/modules/backup_clouds/onedrive/config.py
  packages/modules/backup_clouds/samba/config.py
  packages/modules/electricity_tariffs/awattar/config.py
  packages/modules/electricity_tariffs/energycharts/config.py
  packages/modules/electricity_tariffs/fixed_hours/config.py
  packages/modules/electricity_tariffs/octopusenergy/config.py
  packages/modules/electricity_tariffs/ostrom/config.py
  packages/modules/electricity_tariffs/rabot/config.py
  packages/modules/electricity_tariffs/tibber/config.py
  packages/modules/electricity_tariffs/voltego/config.py
  packages/modules/monitoring/zabbix/config.py
  packages/modules/vehicles/aiways/config.py
  packages/modules/vehicles/bmwbc/config.py
  packages/modules/vehicles/evcc/config.py
  packages/modules/vehicles/evnotify/config.py
  packages/modules/vehicles/http/config.py
  packages/modules/vehicles/json/config.py
  packages/modules/vehicles/kia/config.py
  packages/modules/vehicles/manual/config.py
  packages/modules/vehicles/mqtt/config.py
  packages/modules/vehicles/ovms/config.py
  packages/modules/vehicles/polestar/config.py
  packages/modules/vehicles/psa/config.py
  packages/modules/vehicles/psacc/config.py
  packages/modules/vehicles/renault/config.py
  packages/modules/vehicles/skodaconnect/config-disabled.py
  packages/modules/vehicles/smarthello/config.py
  packages/modules/vehicles/tesla/config.py
  packages/modules/vehicles/tronity/config.py
  packages/modules/vehicles/vwid/config.py
  runs/atreboot.sh
Labels: enhancement, ui

#1908 Feature restructure backup
  packages/helpermodules/subdata.py
  runs/atreboot.sh
  runs/backup.sh
  runs/factory_reset.sh
  runs/prepare_restore.sh
  runs/restore.sh
Labels: enhancement, ui

#1682 Add a SoC module for Nissan Leaf till MY 2019
  packages/modules/conftest.py
  packages/modules/vehicles/leaf/__init__.py
  packages/modules/vehicles/leaf/api.py
  packages/modules/vehicles/leaf/config.py
  packages/modules/vehicles/leaf/soc.py
  requirements.txt
Labels: enhancement, ui

#2330 Fixing link to first steps in openWB 2
  docs/Home.md
Labels: documentation

#2339 SonnenBatterie
  packages/modules/devices/sonnen/sonnenbatterie/api.py
  packages/modules/devices/sonnen/sonnenbatterie/bat.py
  packages/modules/devices/sonnen/sonnenbatterie/config.py
  packages/modules/devices/sonnen/sonnenbatterie/counter.py
  packages/modules/devices/sonnen/sonnenbatterie/counter_consumption.py
  packages/modules/devices/sonnen/sonnenbatterie/device.py
  packages/modules/devices/sonnen/sonnenbatterie/inverter.py
Labels: bug

#2343 SonnenBatterie: fix counter/inverter state
  packages/modules/devices/sonnen/sonnenbatterie/api.py
Labels: bug
