Repository openWB/core, pull requests merged in 2025-03, with the labels that each got.

#2219 don't wait for phase switch and switch off immediately after charge or submode change
  packages/control/algorithm/surplus_controlled.py
Labels: enhancement

#2190 update valid topics
  packages/control/ev/charge_template.py
  packages/control/optional.py
  packages/helpermodules/update_config.py
Labels: enhancement

#2234 UPower
  packages/modules/devices/upower/__init__.py
  packages/modules/devices/upower/upower/__init__.py
  packages/modules/devices/upower/upower/bat.py
  packages/modules/devices/upower/upower/config.py
  packages/modules/devices/upower/upower/counter.py
  packages/modules/devices/upower/upower/device.py
  packages/modules/devices/upower/upower/inverter.py
  packages/modules/devices/upower/upower/version.py
  packages/modules/devices/upower/vendor.py
Labels: enhancement, ui

#2214 Feature: Octopus Energy ElectricityTariff
  packages/modules/electricity_tariffs/octopusenergy/config.py
  packages/modules/electricity_tariffs/octopusenergy/tariff.py
Labels: enhancement, ui

#2188 add ostrom electricity tariff
  packages/modules/electricity_tariffs/ostrom/__init__.py
  packages/modules/electricity_tariffs/ostrom/config.py
  packages/modules/electricity_tariffs/ostrom/tariff.py
Labels: enhancement, ui

#2252 percentage for import counters
  packages/helpermodules/measurement_logging/conftest.py
  packages/helpermodules/measurement_logging/process_log.py
  packages/helpermodules/measurement_logging/process_log_test.py
Labels: enhancement, ui

#2210 soc module vwid improvements
  packages/modules/vehicles/vwid/api.py
  packages/modules/vehicles/vwid/config.py
  packages/modules/vehicles/vwid/soc.py
Labels: enhancement, ui

#2208 SOC Module bmwbc improvements
  packages/modules/vehicles/bmwbc/api.py
Labels: enhancement, ui

#2170 Feature fixed hour tariff
  packages/modules/electricity_tariffs/fixed_hours/__init__.py
  packages/modules/electricity_tariffs/fixed_hours/config.py
  packages/modules/electricity_tariffs/fixed_hours/tariff.py
Labels: enhancement, ui

#2241 [ADD] Nibe S-Series Power Consumption Smarthome
  packages/modules/smarthome/nibe/__init__.py
  packages/modules/smarthome/nibe/smartnibe.py
  packages/modules/smarthome/nibe/watt.py
  packages/smarthome/smartcommon.py
Labels: enhancement, ui

#2254 chart command
  packages/helpermodules/command.py
Labels: bug, ui

#2281 standard-legacy: add configurable chart range
  packages/modules/web_themes/standard_legacy/config.py
  packages/modules/web_themes/standard_legacy/web/electricityPriceChart.js
  packages/modules/web_themes/standard_legacy/web/index.html
  packages/modules/web_themes/standard_legacy/web/livechart.js
  packages/modules/web_themes/standard_legacy/web/processAllMqttMsg.js
  packages/modules/web_themes/standard_legacy/web/setupMqttServices.js
  packages/modules/web_themes/standard_legacy/web/smartHome.html
Labels: enhancement
